//
//  DreamRightSK.swift
//  DreamRight
//
//  Created by Kevin Sullivan on 11/2/14.
//  Copyright (c) 2014 SideApps. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class DreamRightSK : NSObject {
    
    //// Cache
    
    private struct Cache {
        static var color: UIColor = UIColor(red: 0.055, green: 0.114, blue: 0.290, alpha: 1.000)
        static var color2: UIColor = UIColor(red: 0.992, green: 0.902, blue: 0.239, alpha: 1.000)
    }
    
    //// Colors
    
    public class var color: UIColor { return Cache.color }
    public class var color2: UIColor { return Cache.color2 }
    
    //// Drawing Methods
    
    public class func drawIconCanvas(frame: CGRect) {
        
        
        //// Subframes
        let group: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.02830 + 0.5), frame.minY + floor(frame.height * 0.02830 - 0.36) + 0.86, floor(frame.width * 0.96713 - 0.02) - floor(frame.width * 0.02830 + 0.5) + 0.52, floor(frame.height * 0.97302 + 0.5) - floor(frame.height * 0.02830 - 0.36) - 0.86)
        
        
        //// Group
        //// Moon Drawing
        var moonPath = UIBezierPath()
        moonPath.moveToPoint(CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.71616 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.49340 * group.width, group.minY + 0.54028 * group.height), controlPoint1: CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.71616 * group.height), controlPoint2: CGPointMake(group.minX + 0.63746 * group.width, group.minY + 0.72511 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.48152 * group.width, group.minY + 0.00000 * group.height), controlPoint1: CGPointMake(group.minX + 0.34935 * group.width, group.minY + 0.35546 * group.height), controlPoint2: CGPointMake(group.minX + 0.48152 * group.width, group.minY + 0.00000 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.20817 * group.width, group.minY + 0.11745 * group.height), controlPoint1: CGPointMake(group.minX + 0.48152 * group.width, group.minY + 0.00000 * group.height), controlPoint2: CGPointMake(group.minX + 0.35536 * group.width, group.minY + 0.01562 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.04179 * group.width, group.minY + 0.30538 * group.height), controlPoint1: CGPointMake(group.minX + 0.08932 * group.width, group.minY + 0.19967 * group.height), controlPoint2: CGPointMake(group.minX + 0.05367 * group.width, group.minY + 0.28189 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.00613 * group.width, group.minY + 0.57552 * group.height), controlPoint1: CGPointMake(group.minX + -0.00575 * group.width, group.minY + 0.39934 * group.height), controlPoint2: CGPointMake(group.minX + -0.00469 * group.width, group.minY + 0.48348 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.08932 * group.width, group.minY + 0.78694 * group.height), controlPoint1: CGPointMake(group.minX + 0.01757 * group.width, group.minY + 0.67279 * group.height), controlPoint2: CGPointMake(group.minX + 0.06203 * group.width, group.minY + 0.74774 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.31396 * group.width, group.minY + 0.95586 * group.height), controlPoint1: CGPointMake(group.minX + 0.11605 * group.width, group.minY + 0.82533 * group.height), controlPoint2: CGPointMake(group.minX + 0.20104 * group.width, group.minY + 0.90985 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.60713 * group.width, group.minY + 0.99724 * group.height), controlPoint1: CGPointMake(group.minX + 0.41390 * group.width, group.minY + 0.99659 * group.height), controlPoint2: CGPointMake(group.minX + 0.53361 * group.width, group.minY + 1.00540 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 0.81655 * group.width, group.minY + 0.91445 * group.height), controlPoint1: CGPointMake(group.minX + 0.68023 * group.width, group.minY + 0.98912 * group.height), controlPoint2: CGPointMake(group.minX + 0.75943 * group.width, group.minY + 0.95617 * group.height))
        moonPath.addCurveToPoint(CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.71616 * group.height), controlPoint1: CGPointMake(group.minX + 0.91810 * group.width, group.minY + 0.84027 * group.height), controlPoint2: CGPointMake(group.minX + 1.00000 * group.width, group.minY + 0.71616 * group.height))
        moonPath.closePath()
        DreamRightSK.color2.setFill()
        moonPath.fill()
        DreamRightSK.color2.setStroke()
        moonPath.lineWidth = 1
        moonPath.stroke()
        
        
        //// StarBig Drawing
        var starBigPath = UIBezierPath()
        starBigPath.moveToPoint(CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.24078 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.19158 * group.width, group.minY + 0.29583 * group.height), controlPoint1: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.24078 * group.height), controlPoint2: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.27748 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.24729 * group.width, group.minY + 0.31419 * group.height), controlPoint1: CGPointMake(group.minX + 0.21015 * group.width, group.minY + 0.31419 * group.height), controlPoint2: CGPointMake(group.minX + 0.24729 * group.width, group.minY + 0.31419 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.19158 * group.width, group.minY + 0.33254 * group.height), controlPoint1: CGPointMake(group.minX + 0.24729 * group.width, group.minY + 0.31419 * group.height), controlPoint2: CGPointMake(group.minX + 0.21015 * group.width, group.minY + 0.31419 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.38759 * group.height), controlPoint1: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.35089 * group.height), controlPoint2: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.38759 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.15444 * group.width, group.minY + 0.33254 * group.height), controlPoint1: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.38759 * group.height), controlPoint2: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.35089 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.09873 * group.width, group.minY + 0.31419 * group.height), controlPoint1: CGPointMake(group.minX + 0.13587 * group.width, group.minY + 0.31419 * group.height), controlPoint2: CGPointMake(group.minX + 0.09873 * group.width, group.minY + 0.31419 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.15444 * group.width, group.minY + 0.29583 * group.height), controlPoint1: CGPointMake(group.minX + 0.09873 * group.width, group.minY + 0.31419 * group.height), controlPoint2: CGPointMake(group.minX + 0.13587 * group.width, group.minY + 0.31419 * group.height))
        starBigPath.addCurveToPoint(CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.24078 * group.height), controlPoint1: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.27748 * group.height), controlPoint2: CGPointMake(group.minX + 0.17301 * group.width, group.minY + 0.24078 * group.height))
        starBigPath.closePath()
        starBigPath.lineCapStyle = kCGLineCapRound;
        
        starBigPath.lineJoinStyle = kCGLineJoinBevel;
        
        DreamRightSK.color.setFill()
        starBigPath.fill()
        DreamRightSK.color.setStroke()
        starBigPath.lineWidth = 1
        starBigPath.stroke()
        
        
        //// StarMedium Drawing
        var starMediumPath = UIBezierPath()
        starMediumPath.moveToPoint(CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.39347 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.25249 * group.width, group.minY + 0.43531 * group.height), controlPoint1: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.39347 * group.height), controlPoint2: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.42136 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.29483 * group.width, group.minY + 0.44926 * group.height), controlPoint1: CGPointMake(group.minX + 0.26660 * group.width, group.minY + 0.44926 * group.height), controlPoint2: CGPointMake(group.minX + 0.29483 * group.width, group.minY + 0.44926 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.25249 * group.width, group.minY + 0.46321 * group.height), controlPoint1: CGPointMake(group.minX + 0.29483 * group.width, group.minY + 0.44926 * group.height), controlPoint2: CGPointMake(group.minX + 0.26660 * group.width, group.minY + 0.44926 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.50505 * group.height), controlPoint1: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.47715 * group.height), controlPoint2: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.50505 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.22427 * group.width, group.minY + 0.46321 * group.height), controlPoint1: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.50505 * group.height), controlPoint2: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.47715 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.18193 * group.width, group.minY + 0.44926 * group.height), controlPoint1: CGPointMake(group.minX + 0.21015 * group.width, group.minY + 0.44926 * group.height), controlPoint2: CGPointMake(group.minX + 0.18193 * group.width, group.minY + 0.44926 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.22427 * group.width, group.minY + 0.43531 * group.height), controlPoint1: CGPointMake(group.minX + 0.18193 * group.width, group.minY + 0.44926 * group.height), controlPoint2: CGPointMake(group.minX + 0.21015 * group.width, group.minY + 0.44926 * group.height))
        starMediumPath.addCurveToPoint(CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.39347 * group.height), controlPoint1: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.42136 * group.height), controlPoint2: CGPointMake(group.minX + 0.23838 * group.width, group.minY + 0.39347 * group.height))
        starMediumPath.closePath()
        starMediumPath.lineCapStyle = kCGLineCapRound;
        
        starMediumPath.lineJoinStyle = kCGLineJoinBevel;
        
        DreamRightSK.color.setFill()
        starMediumPath.fill()
        DreamRightSK.color.setStroke()
        starMediumPath.lineWidth = 1
        starMediumPath.stroke()
        
        
        //// StarSmall Drawing
        var starSmallPath = UIBezierPath()
        starSmallPath.moveToPoint(CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.38172 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.11136 * group.width, group.minY + 0.41035 * group.height), controlPoint1: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.38172 * group.height), controlPoint2: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.40081 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.14033 * group.width, group.minY + 0.41989 * group.height), controlPoint1: CGPointMake(group.minX + 0.12102 * group.width, group.minY + 0.41989 * group.height), controlPoint2: CGPointMake(group.minX + 0.14033 * group.width, group.minY + 0.41989 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.11136 * group.width, group.minY + 0.42944 * group.height), controlPoint1: CGPointMake(group.minX + 0.14033 * group.width, group.minY + 0.41989 * group.height), controlPoint2: CGPointMake(group.minX + 0.12102 * group.width, group.minY + 0.41989 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.45807 * group.height), controlPoint1: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.43898 * group.height), controlPoint2: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.45807 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.09205 * group.width, group.minY + 0.42944 * group.height), controlPoint1: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.45807 * group.height), controlPoint2: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.43898 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.06308 * group.width, group.minY + 0.41989 * group.height), controlPoint1: CGPointMake(group.minX + 0.08239 * group.width, group.minY + 0.41989 * group.height), controlPoint2: CGPointMake(group.minX + 0.06308 * group.width, group.minY + 0.41989 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.09205 * group.width, group.minY + 0.41035 * group.height), controlPoint1: CGPointMake(group.minX + 0.06308 * group.width, group.minY + 0.41989 * group.height), controlPoint2: CGPointMake(group.minX + 0.08239 * group.width, group.minY + 0.41989 * group.height))
        starSmallPath.addCurveToPoint(CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.38172 * group.height), controlPoint1: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.40081 * group.height), controlPoint2: CGPointMake(group.minX + 0.10171 * group.width, group.minY + 0.38172 * group.height))
        starSmallPath.closePath()
        starSmallPath.lineCapStyle = kCGLineCapRound;
        
        starSmallPath.lineJoinStyle = kCGLineJoinBevel;
        
        DreamRightSK.color.setFill()
        starSmallPath.fill()
        DreamRightSK.color.setStroke()
        starSmallPath.lineWidth = 1
        starSmallPath.stroke()
    }
    
    //// Generated Images
    
    public class func imageOfIconCanvas(frame: CGRect) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(110, 110), false, 0)
        DreamRightSK.drawIconCanvas(frame)
        var imageOfIconCanvas = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return imageOfIconCanvas!
    }
    
}

@objc protocol StyleKitSettableImage {
    var image: UIImage! { get set }
}

@objc protocol StyleKitSettableSelectedImage {
    var selectedImage: UIImage! { get set }
}
